name: Update NB1 Program

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  update-html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Run generator script
        run: |
          python generate-nb1.py
      - name: Commit and push
        run: |
          git config user.name "nb1-bot"
          git config user.email "nb1-bot@users.noreply.github.com"
          git add nb1-ungaria-program.html
          git commit -m "Actualizare automată program NB1" || echo "Nimic de actualizat"
          git push
